---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: azure-vote
  namespace: {ENV_NAME}-kaizentm
spec:
  targetNamespace: {ENV_NAME}-kaizentm
  interval: 1m0s
  path: ./azure-vote/manifest
  prune: false
  serviceAccountName: kaizentm
  sourceRef:
    kind: GitRepository
    name: {GIT_REPOSITORY_NAME}

