---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: yakuza
  name: dev-yakuza

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: yakuza
  name: yakuza
  namespace: dev-yakuza

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: yakuza
  name: yakuza-reconciler
  namespace: dev-yakuza
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:dev-yakuza:reconciler
- kind: ServiceAccount
  name: yakuza
  namespace: dev-yakuza

