apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: stage-flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: stage-flux-system
  path: ./infra/pacific-aks
  prune: true
  validation: client