---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: arc-cicd-cluster
  namespace: dev-arcpg-gh
spec:
  # targetNamespace: dev-arcpg-gh
  interval: 1m0s
  path: ./arc-cicd-cluster/manifest
  prune: false
  serviceAccountName: arcpg
  sourceRef:
    kind: GitRepository
    name: arcpg-manifests

