apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dev-flux-system
  namespace: dev-flux-system
spec:
  interval: 1m0s
  ref:
    branch: dev
  url: https://github.com/kaizentm/multicluster-gitops
---