apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: {ENV_NAME}-flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: {ENV_NAME}-flux-system
  path: ./infra/{CLUSTER_NAME}
  prune: true
  validation: client