---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: azure-vote
  namespace: stage-1-0-x-kaizentm
spec:
  targetNamespace: stage-1-0-x-kaizentm
  interval: 1m0s
  path: ./azure-vote/manifest
  prune: false
  serviceAccountName: kaizentm
  sourceRef:
    kind: GitRepository
    name: kaizentm-1-0-x-manifests

